#Ponemos un alias para hacer referencia a este stage
FROM node:14.17.4-alpine3.14 as build
#Creamos este directorio y nos movemos a él
WORKDIR /Blog
#Copiamos el frontend al directorio del contenedor
COPY ../ ./

FROM nginx:stable-alpine
#Instalamos bash
RUN apk --no-cache add bash
#Copiamos el directorio del stage anterior al directorio de este stage
COPY --from=build /Blog /var/www/Blog
COPY ./nginx/blog.com /etc/nginx/conf.d/default.conf